eureka:
  client:
    serviceUrl:
      defaultZone: http://ctx-eureka-server1:19001/eureka/, http://ctx-eureka-server2:19002/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9036
spring:
  application:
    name: CNTService
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#开放所有页面节点  默认只开启了health、info两个节点
  datasource:
    url: ${aws.ps.datasource.url.file.service}
    username: ${aws.ps.datasource.username}
    password: ${aws.ps.datasource.password}
    driver-class-name: org.mariadb.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'

multipart:
  enabled: true


logging:
  level:
    root: INFO
  config: classpath:logging-config-aws.xml

awsParameterStorePropertySource:
  enabled: true

awsParameterStoreSource:
  ssmClient:
    endpointConfiguration:
      endpoint: https://ssm.ap-southeast-1.amazonaws.com
      signingRegion: ap-southeast-1